version: "3.7"

services:
  eureka:
    image: scaffold-eureka:0.0.1-SNAPSHOT
    volumes:
      - /tmp:/tmp
    ports:
      - 8761:8761
    networks:
      - scaffold-cloud
  zuul:
    image: scaffold-zuul:0.0.1-SNAPSHOT
    volumes:
      - /tmp:/tmp
    ports:
      - 8861:8861
    networks:
      - scaffold-cloud

networks:
  scaffold-cloud:
    name: scaffold-cloud
    driver: bridge