eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8850
spring:
  application:
    name: scaffold-sys-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8