eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8850
spring:
  application:
    name: scaffold-sys-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/base?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: true
    check-location: true
    locations: classpath:db/migration/ddl,classpath:db/migration/dml
    validate-on-migrate: true
    clean-on-validation-error: false
    encoding: UTF-8
    baseline-on-migrate: true
    placeholder-prefix: #{.
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
  reasonable: true
  params: pageNum=pageHelperStart;pageSize=pageHelperRows;
  support-methods-arguments: false

logging:
  config: classpath:config/@environment@/logback-spring.xml
  path: /scaffold/log
  file: ${spring.application.name:scaffold-sys-service}

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.cms.scaffold.micro
