steps:
  - label: "test which environment"
    command: ./.scripts/demo.sh

  - wait

  - label: ":maven: mvn package & recreate docker image"
    command: ./.scripts/recreate-docker-image.sh

  - wait

  - label: ":docker: start docker-compose"
    command: ./.scripts/start-docker-service.sh