server:
  port: 7970
spring:
  application:
    name: tx-manager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tx-manager?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: localhost
    password: pwd8ok8
    port: 6379
    database: 3
    timeout: 10000
    jedis:
      pool:
        min-idle: 0
        max-idle: 100
  data:
    redis:
      repositories:
        enabled: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
tx-lcn:
  ribbon:
    loadbalancer:
      dtx:
        enabled: true
  client:
    manager-address: 127.0.0.1
  manager:
    port: 8890
    heart-time: 300000
    dtx-time: 8000
    admin-key: admin
    dtx-lock-time: 10000
  logger:
    enabled: false

